version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:RELEASE.2018-05-11T00-29-24Z
  networks:
    - minio
  volumes:
   - D:\Users\TOS\docker\docker-rsync\storage\to:/data
  ports:
   - "9000:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server data

networks:
  minio:
    driver: bridge