version: '2'

services:
  rsync.from:
    image: shocki/rsync-from
    container_name: rsync.from
    networks:
      - rsync
    volumes:
      - D:\Users\TOS\docker\docker-rsync\storage\from:/data
  rsync.to:
    image: shocki/rsync-to
    container_name: rsync.to
    networks:
      - rsync
    volumes:
      - D:\Users\TOS\docker\docker-rsync\storage\to:/data

networks:
  rsync:
    driver: bridge